export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const UPDATE_PRODUCT_DETAILS = "UPDATE_PRODUCT_DETAILS";
export const GET_CONFIGURATION = "GET_CONFIGURATION";
export const GET_TRL = "GET_TRL";
export const UPDATE_TRL = "UPDATE_TRL";
export const ADD_TRL = "ADD_TRL";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_BUSINESSMODEL = "ADD_BUSINESSMODEL";
