export const ActionTypes = {
    USER_TYPES: {
        SET_USER_DETAIL: "SET_USER_DETAIL",
        SET_USER_ACCOUNT_SETTING: "SET_USER_ACCOUNT_SETTING",
        SET_USER_INFORMATION: "SET_USER_INFORMATION",
        CLEAR_USER_ACCOUNT_SETTING: "CLEAR_USER_ACCOUNT_SETTING",
        CLEAR_USER_INFORMATION: "CLEAR_USER_INFORMATION"
    }
};