const CONFIG_ACTIONS = {
  LOADING: "LOADING",
  CONFIGURATION_LOADED: "CONFIGURATION_LOADED"
};

const PRODUCT_ACTION = {
  LOADING: "LOADING",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  SAVE_PRODUCT: "SAVE_PRODUCT",
  CLEAR_PRODUCT: "CLEAR_PRODUCT",
  FETCH_TRL: "FETCH_TRL"
};

export { CONFIG_ACTIONS, PRODUCT_ACTION };
