export const FETCH_TRL_PENDING = "FETCH_TRL_PENDING";
export const FETCH_TRL_FAILURE = "FETCH_TRL_FAILURE";
export const FETCH_TRL_SUCCESS = "FETCH_TRL_SUCCESS";

export default [FETCH_TRL_SUCCESS, FETCH_TRL_PENDING, FETCH_TRL_FAILURE];
