export const ProductActionTypes = {
    FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILURE: 'FETCH_PRODUCT_FAILURE',
    FETCH_TRL_SUCCESS: 'FETCH_TRL_SUCCESS',
    FETCH_TRL_FAILURE: 'FETCH_TRL_FAILURE',
    UPDATE_TRL: 'UPDATE_TRL',
    UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
    UPDATE_BUSINESS_MODELS: 'UPDATE_BUSINESS_MODELS',
    SET_ACTIVE_TAB: 'SET_ACTIVE_TAB'
}