const configTypes = {
  GET_CONFIG_ERROR: 'GET_CONFIG_ERROR',
  GET_CONFIG_SUCCESS: 'GET_CONFIG_SUCCESS',
  GET_CONFIG_LOADING: 'GET_CONFIG_LOADING',
  CLEAR_CONFIG_ERRORS: 'CLEAR_CONFIG_ERRORS'
};

export default configTypes;
