/** @format */
const productTypes = {
	PRODUCT_ERROR: 'PRODUCT_ERROR',
	PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
	PRODUCT_LOADING: 'PRODUCT_LOADING',
	CLEAR_PRODUCT_ERRORS: 'CLEAR_PRODUCT_ERRORS',

	EDIT_PRODUCT_ERROR: 'EDIT_PRODUCT_ERROR',
	EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
	EDIT_PRODUCT_LOADING: 'EDIT_PRODUCT_LOADING',
};

export default productTypes;
