export const FETCH_CONFIGURATION_PENDING = "FETCH_CONFIGURATION_PENDING";
export const FETCH_CONFIGURATION_FAILURE = "FETCH_CONFIGURATION_FAILURE";
export const FETCH_CONFIGURATION_SUCCESS = "FETCH_CONFIGURATION_SUCCESS";

export default [
    FETCH_CONFIGURATION_PENDING,
    FETCH_CONFIGURATION_FAILURE,
    FETCH_CONFIGURATION_SUCCESS,
];
